//var song = new Audio("betterTogether.mp3");
<<<<<<< HEAD
var images = ['<div class="carousel-item"><img src="images/IMG_0005.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0006.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0007.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0008.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0009.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0010.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0012.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0014.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0019.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0020.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0021.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0023.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0024.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0025.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0026.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0048.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0069.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0135.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0147.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0154.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0203.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0213.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0236.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0241.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0316.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0356.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0379.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0397.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0442.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0469.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0508.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0527.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0528.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0543.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0609.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0619.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0659.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0673.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0675.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0735.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0738.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0763.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0799.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0830.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0836.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0849.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0869.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0922.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0988.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0994.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_0995.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1013.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1123.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1127.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1128.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1142.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1234.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1249.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1296.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1395.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1458.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1461.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1467.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1470.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1488.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1662.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1699.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1847.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1867.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1881.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1914.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1968.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_1982.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2012.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2035.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2140.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2177.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2182.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2201.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2225.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2230.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2276.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2282.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2297.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2335.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2345.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2346.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2398.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2400.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2403.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2408.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2461.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2481.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2488.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2528.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2543.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2584.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2585.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2617.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2666.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2717.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2776.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2882.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_2912.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3062.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3088.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3092.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3095.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3104.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3149.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3157.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3162.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3179.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3246.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3259.PNG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3260.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3266.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3445.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3473.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3485.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3578.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3615.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3702.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3721.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3728.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3784.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3788.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3790.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3800.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3817.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3939.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_3977.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4008.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4093.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4172.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4190.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4272.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4298.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4345.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4385.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4407.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4433.jpeg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4444.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4493.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4504.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4521.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4522.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4539.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4690.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_4711.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_5128.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_5151.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_5459.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_5541.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_5701.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_5799.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_5860.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6128.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6130.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6202.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6213.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6248.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6260.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6278.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6288.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6325.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6343.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6422.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6777.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6784.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6903.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6928.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_6929.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7003.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7031.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7171.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7194.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7196.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7204.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7366.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7485.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7582.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7597.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7599.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7637.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7702.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7703.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7764.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7785.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7802.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7824.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7873.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7891.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7893.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_7960.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_8120.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_8175.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_8323.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_8356.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_8414.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_8420.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_8562.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_8757.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9115.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9118.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9124.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9152.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9162.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9196.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9213.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9229.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9300.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9314.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9325.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9327.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9329.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9360.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9364.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9444.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9505.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9590.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9703.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9771.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9792.JPEG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9847.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9904.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9907.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9921.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9938.jpg" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9941.JPG" class="d-block w-100" alt="image"></div>',
'<div class="carousel-item"><img src="images/IMG_9960.jpg" class="d-block w-100" alt="image"></div>',]

$(document).ready( function(){
  while(images.length){
    var index = Math.floor(Math.random()*images.length);
    $(".carousel-inner").append(images.splice(index,1)[0]);
  }
  document.querySelector(".carousel-item").classList.add("active");
})
=======
>>>>>>> 26e8e9e8e4467320bd8ad7b60462278469193abc

$(".ParkerButton").click( function() {
  console.log("clicked");
  $("#NoeLetter").collapse("hide");
});


$(".NoeButton").click( function() {
  console.log("clicked");
  $("#ParkerLetter").collapse("hide");
});

$(".carousel-inner").click( function() {
  console.log("clicked");
  $("#carouselSlideshow").toggleClass("carousel-fade");
});

// $(".down-arrow").click( function() {
//   console.log("clicked");
//   if(song.paused){
//     song.play();
//   }
//   else{
//     song.pause();
//   }
<<<<<<< HEAD
//
=======

>>>>>>> 26e8e9e8e4467320bd8ad7b60462278469193abc
// });
